project_id = "ppdsxgkmnmjfwmpnamts"

[functions.goal-reminders]
verify_jwt = false

[functions.review-notification]
verify_jwt = false

[functions.review-acknowledgment-notification]
verify_jwt = false

[functions.leave-status-notification]
verify_jwt = false

[functions.leave-submission-notification]
verify_jwt = false

[functions.onboarding-notification]
verify_jwt = false

[functions.onboarding-reminders]
verify_jwt = false

[functions.event-notification]
verify_jwt = false
