project_id = "ppdsxgkmnmjfwmpnamts"

[functions.goal-reminders]
verify_jwt = false

[functions.review-notification]
verify_jwt = false

[functions.review-acknowledgment-notification]
verify_jwt = false

[functions.leave-status-notification]
verify_jwt = false
